services:
  tradutor:
    container_name: tradutor
    environment:
      - PUBLIC_URL=http://localhost:3001
    ports:
      - "3001:3000"
    networks:
      - npm-net

networks:
  npm-net:
    external: false
    name: tradutor-local
