services:
  tradutor:
    build: .
    container_name: tradutor
    restart: always
    networks:
      - npm-net
    environment:
      - PUBLIC_URL=https://tradutor.omcx.ddns.net
    ports:
      - "3001:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  npm-net:
    external: true
